x-global-env: &global-env
  env_file:
    - .env

services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:v1.13.6
    ports:
      - 6333:6333
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
    restart: always

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    volumes:
      - ./data/minio_storage:/data
    command: server --console-address ":9001" /data
    restart: always
    <<: *global-env