x-global-env: &global_env
  env_file:
    - .env

services:
  mysql:
    image: mysql:9
    <<: *global_env
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - ./mysql_storage:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  
  qdrant:
    image: qdrant/qdrant:v1.13.4
    <<: *global_env
    restart: always
    ports:
      - 6333:6333
    volumes:
      - ./qdrant_storage:/qdrant/storage
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  connector-check:
    image: python:3.12-alpine
    <<: *global_env
    depends_on:
      mysql:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    environment:
      - DOCKER_HOST=1
    working_dir: /app
    volumes:
      - ./healthcheck:/app
    command: >
      sh -c "pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir &&
      python cnn_check.py"