x-global-env: &global-env
  env_file:
    - .env

services:
  qdrant:
    container_name: qdrant
    image: thanaraklee/qdrant-rootlee:1.0.0
    ports:
      - 6333:6333
    restart: always

  minio:
    container_name: minio
    image: thanaraklee/minio-rootlee:1.0.0
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    command: server --console-address ":9001" /data
    restart: always
    <<: *global-env